# Generated by Django 5.2.12 on 2026-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_make_project_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='before_logo',
            field=models.CharField(blank=True, default='Innovate • Build • Deploy', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading',
            field=models.TextField(blank=True, help_text='Main heading for hero section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Right side image for hero section', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheading',
            field=models.TextField(blank=True, help_text='Subheading for hero section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_heading',
            field=models.CharField(blank=True, default='Welcome to Our Platform', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_display_name',
            field=models.CharField(blank=True, default='Portfolio Projects', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, default='AI Developer Platform', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='subheading',
            field=models.TextField(blank=True),
        ),
    ]
