# Generated by Django 5.2.12 on 2026-04-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_sitesettings_before_logo_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button1_is_primary',
            field=models.BooleanField(default=True, help_text='Make this the primary button'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button1_text',
            field=models.CharField(blank=True, default='Initiate Deployment', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button1_url',
            field=models.CharField(blank=True, default='/admin', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button2_is_primary',
            field=models.BooleanField(default=False, help_text='Make this the primary button'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button2_text',
            field=models.CharField(blank=True, default='View Technical Specs', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button2_url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
