# Generated by Django 5.2.12 on 2026-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_sitesettings_hero_button1_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_font_family',
            field=models.CharField(blank=True, default='Inter, sans-serif', help_text='Font family for hero heading', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading_font_size',
            field=models.CharField(blank=True, default='4rem', help_text='Font size for hero heading (e.g., 4rem, 64px)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_height',
            field=models.CharField(blank=True, default='auto', help_text='Height for hero image (e.g., auto, 400px)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_width',
            field=models.CharField(blank=True, default='100%', help_text='Width for hero image (e.g., 100%, 500px)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheading_font_family',
            field=models.CharField(blank=True, default='Inter, sans-serif', help_text='Font family for hero subheading', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheading_font_size',
            field=models.CharField(blank=True, default='1.125rem', help_text='Font size for hero subheading (e.g., 1.125rem, 18px)', max_length=20),
        ),
    ]
