# Generated by Django 5.2.12 on 2026-04-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_sitesettings_hero_heading_font_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#3b82f6', help_text='Primary theme color', max_length=20)),
                ('dark_mode', models.BooleanField(default=True, help_text='Enable dark mode')),
                ('font_family', models.CharField(default='Inter, sans-serif', help_text='Default font family', max_length=100)),
                ('font_size', models.CharField(default='16px', help_text='Base font size', max_length=10)),
                ('profile_image', models.URLField(blank=True, help_text='Profile image URL', null=True)),
                ('bio', models.TextField(blank=True, help_text='User bio/description')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Enable push notifications')),
                ('show_profile_publicly', models.BooleanField(default=False, help_text='Show profile in public listings')),
                ('show_email_publicly', models.BooleanField(default=False, help_text='Show email in profile')),
                ('language', models.CharField(default='en', help_text='Interface language', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='User timezone', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core_api.customer')),
            ],
            options={
                'verbose_name': 'Customer Preference',
                'verbose_name_plural': 'Customer Preferences',
            },
        ),
    ]
